# -*- coding: utf-8 -*-
"""analise_produtos_agricola.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JpvaDL1yb9mWV8h69FfmB5Rodlts0Tu3
"""

import pandas as pd

production = pd.read_csv("/content/drive/MyDrive/Production_Crops_Livestock_E_All_Data_(Normalized).csv", encoding='latin-1')

value = pd.read_csv("/content/drive/MyDrive/Value_of_Production_E_All_Data_(Normalized).csv",encoding='latin-1')

from google.colab import drive
drive.mount('/content/drive')

# Atualmente, a taxa de crescimento da população mundial é de 1,1% (ONU, 2020). A
# A população mundial atual é de 7,8 milhões de habitantes e segue um ritmo lento de crescimento.

production.head()

value.head()

brazil_valor = value[value['Area'] == 'Brazil'] 
soja_valor = brazil_valor[brazil_valor['Item'] == 'Soybeans']

soja_valor.tail()

soja_valor_bruto = soja_valor[soja_valor['Element']=='Gross Production Value (constant 2014-2016 thousand I$)']['Value']

valor_bruto_soja = soja_valor_bruto.values

production.head()

brazil = production[production['Area'] == 'Brazil']

soja = brazil[brazil['Item'] == 'Soybeans']

soja.Element.unique()
#'Área colhida', 'Rendimento', 'Produção'

colhida = soja[soja.Element == "Area harvested"]['Value'].values
rendimento = soja[soja.Element == "Yield"]['Value'].values
producao = soja[soja.Element == "Production"]['Value'].values

anos = soja.Year.unique()

anos

crops = soja.Element.unique().tolist()

df = pd.DataFrame([colhida, rendimento, producao, valor_bruto_soja], columns=anos)

df = df.T.reset_index()

df.columns = ['ano', 'colhida', 'rendimento', 'producao', 'valor']

df

"""#Analise exploratória"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.style.use("dark_background")
plt.figure(figsize=(12,8))

sns.lineplot(df['ano'], df['valor'])

import matplotlib.pyplot as plt
fix, ax = plt.subplots(figsize=(15,15))
ax = sns.heatmap(df.corr(), annot=True)

# df = df.fillna(lambda x: x.median())

"""#Pre processamento"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

df = clean_dataset(df)

x = df.iloc[:, 0:4]
y = df.iloc[:, 4:]

"""#Criacao do modelo"""

from keras.layers import LSTM, Dense
from keras.models import Sequential

regressor = Sequential()
regressor.add(Dense(units = 30, activation="relu", input_dim=4))
regressor.add(Dense(units = 30, activation="relu"))
regressor.add(Dense(units = 30, activation="relu"))
regressor.add(Dense(units=1, activation='linear'))
regressor.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_squared_error', 'mean_absolute_error', 'mean_absolute_percentage_error', 'cosine_proximity'])
regressor.fit(x, y, batch_size=2, epochs=5000)

previsoes =regressor.predict(x)

def mean_squared_error(y_true, y_pred):
    return K.mean(K.square(y_pred - y_true), axis=-1)

# O modelo performou muito bem!

media_y = y.mean()

1.226772e+07

media_previsoes = previsoes.mean()

print(f"Media do y real foi de {12267720}, media do modelo foi de  {media_previsoes}")
print(f"Diferenca de {12267720 - media_previsoes}")

# ANO  | Area Plantada | produtividade/rendimento | producao em tonnes
novo_entrada = np.array([[2020.0,      37188168.0,         32752.0,            121797712.0]])

soja[soja['Year'] == 2020]

#Soja no Brasil (maior produtor mundial do grão)
# Produção: 135,409 milhões de toneladas
# Área plantada: 38,502 milhões de hectares
# Produtividade: 3.517 kg/ha
?Fonte: CONAB (Levantamento de 05/2021)
# https://www.embrapa.br/soja/cultivos/soja1/dados-economicos

df.tail(1)

#valor em 2019 foi de:
print(f'A producao do valor bruta da soja foi de : {43703960.0 * 1000 * 4} Bilhoes de reais')
#174.815.840.000 Bilhoes $

df.tail(5)

regressor.predict(novo_entrada)

print(f'A previsao do valor de prodição da soja sera de  : {46511850.0 * 1000 * 4} Bilhoes de reais')

#De acordo com o modelo 2020 sera  de:
#186.047.400.000 Bilhoes R$

# foi de 121,8 milhões de toneladas, gerando R$ 169,1 bilhões. Esse valor é 35,0% superior ao da safra de soja 2019.
#https://www.gov.br/pt-br/noticias/agricultura-e-pecuaria/2021/09/valor-da-producao-agricola-nacional-tem-recorde-em-2020-com-r-470-5-bilhoes#:~:text=A%20produ%C3%A7%C3%A3o%20de%20soja%20do,R%24%20169%2C1%20bilh%C3%B5es.